---
- name: Check kafka dir status
  stat:
    path: '{{ kafka_path }}'
  register: kafka_status
  tags: kafka-install

- name: Download kafka to server
  unarchive:
    src: 'https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ kafka_scala }}-{{ kafka_version }}.tgz'
    dest: /opt
    remote_src: yes
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
  when: ansible_distribution == 'Ubuntu' and kafka_status.stat.exists == false
  tags: kafka-install

- name: Rename kafka dir
  command: 'mv {{ kafka_path }}_{{ kafka_scala }}-{{ kafka_version }} {{ kafka_path }}'
  when: ansible_distribution == 'Ubuntu' and kafka_status.stat.exists == false
  tags: kafka-install

- name:  Add kafka log dir
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    recurse: yes
  loop:
    - '{{ kafka_log_path }}'
  tags: kafka-install

- name: Fix permission for opt
  file:
    path: '{{ opt_path }}'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    recurse: yes
  when: ansible_distribution == 'Ubuntu'
  tags: kafka-install

- name: Copy kafka server properties
  template:
    src: '{{ template_path }}/config/server.properties'
    dest: '{{ kafka_conf_path }}/server.properties'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
  tags: kafka-conf
  when: "'dev' not in inventory_hostname"
  notify: 'restart supervisorctl kafka'

- name: Copy kafka configuration to server
  template:
    src: '{{ template_path }}/supervisor/kafka.conf'
    dest: '{{ supervisor_conf_path }}/kafka.conf'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
  tags: kafka-conf
  when: "'dev' not in inventory_hostname"
  notify: 'restart supervisorctl kafka'
