---
- name: Get current path status
  stat:
    path: "/etc/localtime"
  register: current_localtime

- name: Delete if current path link exist
  file:
    path: "/etc/localtime"
    state: absent
  when: current_localtime.stat.islnk is defined and current_localtime.stat.islnk

- name: Create new link
  file:
    src: "/usr/share/zoneinfo/Asia/Jakarta"
    dest: "/etc/localtime"
    state: link
    force: true
