- name: Install Zookeeper Cluster
  hosts: "{{ host }}"
  become: yes
  vars_files:
    - "{{ vault_file }}"
  roles:
    # misc
    - misc/supervisor
    - misc/setdatetime
    - misc/java11
    - misc/unzip
    # exporter
    - exporter
    # zookeeper
    - zookeeper
